const initialState = {
  userAccount: [],
  listCar: [],
  booking: [],
  isLogin: false,
  carsOption: [
    {
      id: 1,
      name: "Toyota Vios",
      type: "Sedan",
      image: "https://source.unsplash.com/x06lguTO7Hg",
      status: "available",
      startDate: "2022-06-27",
      endDate: "2022-06-27",
      startBooking: null,
      endBooking: null,
    },
    {
      id: 2,
      name: "Mercedes Benz C Class ",
      type: "Sedan",
      image: "https://source.unsplash.com/DvldeHcqNSE",
      status: "available",
      startDate: "2022-06-27",
      endDate: "2022-06-27",
      startBooking: null,
      endBooking: null,
    },
    {
      id: 3,
      name: "Hyundai Staria ",
      type: "Mini Van",
      image: "https://source.unsplash.com/3mZNCwWnaFw",
      status: "available",
      startDate: "2022-06-27",
      endDate: "2022-06-27",
      startBooking: null,
      endBooking: null,
    },
    {
      id: 4,
      name: "Volkswagen Tosca",
      type: "Mini Van",
      image: "https://source.unsplash.com/GQgybU-u0GQ",
      status: "available",
      startDate: "2022-06-27",
      endDate: "2022-06-27",
      startBooking: null,
      endBooking: null,
    },
    {
      id: 5,
      name: "Cayman ",
      type: "Sport",
      image: "https://source.unsplash.com/TFyha8E8ofo",
      status: "available",
      startDate: "2022-06-27",
      endDate: "2022-06-27",
      startBooking: null,
      endBooking: null,
    },
    {
      id: 6,
      name: "Volkswagen Blue",
      type: "Mini Van",
      image: "https://source.unsplash.com/84a1h0YZP7s",
      status: "available",
      startDate: "2022-06-27",
      endDate: "2022-06-27",
      startBooking: null,
      endBooking: null,
    },
    {
      id: 7,
      name: " Mini Cooper",
      type: "Hatchback",
      image: "https://source.unsplash.com/qXZ89RUhWlA",
      status: "available",
      startDate: "2022-06-27",
      endDate: "2022-06-27",
      startBooking: null,
      endBooking: null,
    },
    {
      id: 8,
      name: " Toyota Land Cruiser",
      type: "SUV",
      image: "https://source.unsplash.com/yAf2NB7Om4c",
      status: "available",
      startDate: "2022-06-27",
      endDate: "2022-06-27",
      startBooking: null,
      endBooking: null,
    },
    {
      id: 9,
      name: "Mustang Blue ",
      type: "sport",
      image: "https://source.unsplash.com/YzCu-V0aKHA",
      status: "available",
      startDate: "2022-06-27",
      endDate: "2022-06-27",
      startBooking: null,
      endBooking: null,
    },
    {
      id: 10,
      name: "VW Red",
      type: "Hatchback",
      image: "https://source.unsplash.com/eM5z-GX10p8",
      status: "available",
      startDate: "2022-06-27",
      endDate: "2022-06-27",
      startBooking: null,
      endBooking: null,
    },
  ],
};

export const whitelist = [
  "userAccout",
  "listCar",
  "booking",
  "isLogin",
  "carOption",
];

export const fileReducer = (state = initialState) => {
  return <div>fileReducer</div>;
};
